#!/usr/bin/env node

var data = {};

// Load basic info.
data.tracks = require('../data/tracks.json');
data.artists = require('../data/artists.json');
data.individuals = require('../data/individuals.json');
data.releases = require('../data/releases.json');

// Load relation data
data.at = require('../data/artist_track.json');
data.ia = require('../data/individual_artist.json');
data.it = require('../data/individual_track.json');
data.tr = require('../data/track_release.json');

data.printTrackInfo = function (track) {
  console.log('Track ID: ' + track._id);

  track.names.forEach(function (title) {
    console.log('\tTitle: ' + title);
  });

  data.printRelatedInfoForTrack({
    track_id: track._id,
    relatedInfo: 'artists',
    relatedField: 'names',
    relationData: 'at',
    relationDataId: 'artist_id',
    label: 'Artist',
  });

  data.printRelatedInfoForTrack({
    track_id: track._id,
    relatedInfo: 'releases',
    relatedField: 'names',
    relationData: 'tr',
    relationDataId: 'release_id',
    label: 'Release',
  });

  data.printRelatedInfoForTrack({
    track_id: track._id,
    relatedInfo: 'individuals',
    relatedField: 'names',
    additionalInfo: 'credits',
    relationData: 'it',
    relationDataId: 'individual_id',
    label: 'Individual',
  });
};

data.printRelatedInfoForTrack = function (options) {

  var extras={};

  // Get all the entries from the relation data structure that are related to this one.
  var relatedIdsAndExtra = data[options.relationData].filter(function (value) {
    return value.track_id === options.track_id;
  });

  // If we want additional info (like credits), grab that now too.
  if (options.additionalInfo) {
    for (var i=0, l=relatedIdsAndExtra.length; i<l; i++) {
      extras[relatedIdsAndExtra[i][options.relationDataId]] =  relatedIdsAndExtra[i][options.additionalInfo] || [];
    }
  }

  // Strip down to just the IDs we requested.
  var relatedIds = relatedIdsAndExtra.map(function (value) {
    return value[options.relationDataId];
  });

  // Get the actual data we want specified by the related IDs.
  var relatedData = data[options.relatedInfo].filter(function (value) {
    return relatedIds.indexOf(value._id) > -1;
  });

  relatedData.forEach(function (value) {
    var extra = '';
    if (extras[value._id] && extras[value._id].length>0) {
      extra = ' (' + extras[value._id].join(', ') + ')';
    }
    for (var i=0, l=value[options.relatedField].length; i<l; i++) {
      console.log('\t' + options.label + ': ' + value[options.relatedField][i] + extra + ' [' + value._id + ']');
    }
  });
};

data.tracks.forEach(data.printTrackInfo);
