#!/usr/bin/env node

/* Writes files for JSON representation of all individuals on tracks with a given individual */

var fs = require("graceful-fs");

var individuals = require("../data/individuals.json");
var individualIds = individuals.map(function(elem) { return elem._id; });
var individual_track = require("../data/individual_track.json");

var getName = function (id) {
  return individuals.filter(function(elem) {
    return elem._id === id;
  })[0].names[0];
};

var generateJson = function (individualId) {
  var sourceLabel = getName(individualId);

  var tracksWithIndividual = individual_track.filter(function (elem) {
    return elem.individual_id === individualId;
  }).map(function (elem) {
    return elem.track_id;
  });

  var connectedIndividuals = individual_track.filter(function (elem) {
    return tracksWithIndividual.indexOf(elem.track_id) > -1 &&
      elem.individual_id != individualId;
  }).map(function (elem) {
    return {source: sourceLabel, target: getName(elem.individual_id)};
  });

  var file = individualId + '.json';
  var formattedOutput = JSON.stringify(connectedIndividuals, null, 2);

  fs.writeFile(file, formattedOutput,
    function (err) {
      if (err) throw err;
    }
  );
};

individualIds.forEach(function (individualId) {
  generateJson(individualId);
});
