#!/usr/bin/env node

/* Returns JSON representation of all individuals on tracks with a given individual */

// TODO: Take operations in here and convert to Data API calls

// var Data = require("../lib/Data");

// var data = new Data();
// data.read(__dirname + "/../data");

// data.getConnected('individuals', '1', 'tracks'); // get all individuals connected by tracks to individual of id '1'

var individuals = require("../data/individuals.json");
var individualId = individuals[0]._id;
var individual_track = require("../data/individual_track.json");

var getName = function (id) {
  return individuals.filter(function(elem) {
    return elem._id === id;
  })[0].names[0];
};


var sourceLabel = getName(individualId);

var tracksWithIndividual = individual_track.filter(function (elem) {
  return elem.individual_id === individualId;
}).map(function (elem) {
  return elem.track_id;
});

var connectedIndividuals = individual_track.filter(function (elem) {
  return tracksWithIndividual.indexOf(elem.track_id) > -1;
}).map(function (elem) {
  return {source: sourceLabel, target: getName(elem.individual_id)};
});

// convert IDs to labels
connectedIndividuals.map(function(elem) {

});

console.dir(connectedIndividuals);

