#!/usr/bin/env node

var Data = require("../lib/data");
var data = new Data();

var actions = ["add"];

var action = process.argv[2];

var args = process.argv.splice(3);

var rv;

switch (action) {
  case "add":
    rv = data.add.apply(data, args);
    if (rv.status === data.StatusEnum.OK) {
        data.write();
    }
    break;
  default:
    console.log("mrd [" + actions.join(" | ") + "] ...");
}
